- name: Install Golang and friends
  become: true
  pacman:
    name: "{{ item }}"
  with_items:
    - go
    - go-tools

- name: Install gocode
  aur:
    name: gocode-git
    user: "{{ ansible_user_id }}"
