- name: Install fish shell and friends
  become: true
  pacman:
    name: "{{ item }}"
  with_items:
    - curl
    - fish
    - fortune-mod
    - most

- name: Install fisher
  aur:
    name: fisherman

- name: Install fisher modules
  include: tasks/fisher_package.yml name={{ item }}
  with_items:
    - z
    - rvm
    - omf/theme-bobthefish
    - pyenv

- name: Install fish customizations
  include: tasks/fisher_package.yml name=abesto src=~/dotfiles/fish-abesto

- name: As last step of bash startup, exec fish
  include: roles/bashrc/tasks/bashrc.yml name=exec-fish.sh src=files/exec-fish.sh priority=99

- name: Create nofish bash flavor
  include: roles/bashrc/tasks/flavor.yml name=nofish

- name: Skip execing fish in the nofish bash flavor
  include: roles/bashrc/tasks/skip.yml flavor=nofish priority=99 name=exec-fish.sh
