- name: Install YubiKey tools
  become: true
  pacman:
    name: "{{ item }}"
  with_items:
    - yubikey-personalization
    - yubikey-personalization-gui

- name: Install YubiKey oath desktop client
  aur:
    name: "yubico-yubioath-desktop"

- name: Enable systemd unit pcscd
  become: true
  systemd:
    name: pcscd
    enabled: true
    state: started
