- hosts: localhost
  gather_subset:
    - "!all"
  roles:
    # Basics
    - ssh_keys
    - unix_utils
    - git
    - monitoring
    - audio
    - network
    # Terminal env
    - bashrc
    - fish
    - keychain
    - tmux
    - ssh
    # GUI env
    - xmonad
    - urxvt
    - lightdm
    - dunst
    - xcompose
    # IDE
    - vim
    - emacs
    - intellij
    - zeal
    # Devenv
    - python
    - nodejs
    - ruby
    - java
    - scala
    - docker
    - easyssh
    - aws
    - terraform
    - packer
    - mysql_client
    # User apps
    - chrome
    - spotify
    - wmail
    - slack
    - gitter
    - yubico
    - dropbox
    - keybase
    - lastpass
    - prey
    # Hardware specific
    - dell_xps_15
    # Prezi specific
    - prezi
    - zoom_us
