- hosts: localhost
  gather_subset:
    - "!all"
  roles:
    # Basics
    - unix_utils
    - git
    - monitoring
    - audio
    # Terminal env
    - bashrc
    - fish
    - keychain
    - tmux
    # GUI env
    - xmonad
    - urxvt
    - lightdm
    - slack
    # IDE
    - vim
    - emacs
    - intellij
    - zeal
    # Languages
    - ruby
    - java
    - scala
    # User apps
    - chrome
    - spotify
    - wmail
