- hosts: localhost
  roles:
    - unix_utils
    - git
    - monitoring
    - bashrc
    - fish
    - keychain
    - tmux
    - urxvt
    - emacs
    - ruby
    - lightdm
    - xmonad
    - chrome
    - spotify
