- hosts: home_desktop
  gather_subset:
    - "!all"
  roles:
    # Basics
    - aur
    - ssh_keys
    - unix_utils
    - git
    - monitoring
    - audio
    - network
    - ufw
    - aspell
    # Terminal env
    - bashrc
    - fish
    - keychain
    - tmux
    - ssh
    - exa
    # GUI env
    - fonts
    - lightdm
    - urxvt
    - dunst
    - xcompose
    - autocutsel
    - xmonad
    # IDE
    - vim
    - emacs
    - jetbrains
    - zeal
    # Devenv
    - sh_dev
    - python
    - nodejs
    - ruby
    - java
    - scala
    - golang
    - docker
    - easyssh
    - terraform
    - packer
    - jid
    # User apps
    - chrome
    - firefox
    - spotify
    - wavebox
    - gitter
    - yubico
    - keybase
    - lastpass
    - borgbackup
    # Bauerbill used for system upgrades
    - bauerbill

- hosts: home_desktop
  roles:
    - elixir
    - nouveau

- hosts: single_role
  roles:
    - "{{ role_to_run | default('') }}"
