- hosts: home_desktop, prezi_dell
  gather_subset:
    - "!all"
  roles:
    # Basics
    - ssh_keys
    - unix_utils
    - ripgrep
    - git
    - monitoring
    - audio
    - network
    - ufw
    # Terminal env
    - bashrc
    - fish
    - keychain
    - tmux
    - ssh
    - exa
    # GUI env
    - fonts
    - xmonad
    - urxvt
    - lightdm
    - dunst
    - xcompose
    - autocutsel
    # IDE
    - vim
    - emacs
    - intellij
    - zeal
    # Devenv
    - sh_dev
    - python
    - nodejs
    - ruby
    - java
    - scala
    - golang
    - docker
    - easyssh
    - terraform
    - packer
    - mysql_client
    # User apps
    - chrome
    - spotify
    - wavebox
    - gitter
    - yubico
    - dropbox
    - keybase
    - lastpass
    - borgbackup
    - tldr

- hosts: prezi_dell
  roles:
    - prezi
    - zoom_us
    - prey
    - aws
  tasks:
    - include: roles/network/tasks/vpn.yml

- hosts: home_desktop
  roles:
    - elixir

- hosts: single_role
  roles:
    - "{{ role_to_run | default('') }}"
