- name: Install snapd
  aur:
    name: snapd

- name: Create /snap symlink for old-style snaps
  become: true
  file:
    src: /var/lib/snapd/snap
    dest: /snap
    state: link

- name: Enable snapd in SystemD
  become: true
  systemd:
    enabled: true
    state: started
    name: snapd
