- name: Symlink {{ src }} from dotfiles repository to {{ dest | default('~/' + src) }}
  file:
    src: ~/dotfiles/{{ src }}
    dest: "{{ dest | default('~/' + src) }}"
    state: link
    force: "{{ force | default(false) }}"
