- name: Install keychain
  become: true
  pacman:
    name: keychain

- name: Initialize keychain on bash startup
  include: roles/bashrc/tasks/bashrc.yml name=keychain src=files/keychain.sh priority=10
