- name: Accept zoom.us deb signing key
  become: true
  apt_key:
    url: https://zoom.us/linux/download/pubkey
    id: 61A7C71D

- name: Install zoom.us
  become: true
  apt:
    deb: https://zoom.us/client/latest/zoom_amd64.deb
