- name: Install Parcellite clipboard manager
  become: true
  pacman:
    package: parcellite

- name: Start Parcellite from xprofile
  include: roles/xprofile/tasks/xprofile.yml
  vars:
    name: parcellite
    priority: 20
    command: parcellite &

- name: Symlink Parcellite config from dotfiles
  include: roles/dotfiles/tasks/symlink.yml src=.config/parcellite
