- name: Add NodeSource deb signing key
  become: true
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key

- name: Add NodeSource apt repository
  become: true
  apt_repository:
    repo: "{{ item }}"
  with_items:
    - "deb https://deb.nodesource.com/node_8.x {{ ansible_distribution_release }} main"
    - "deb-src https://deb.nodesource.com/node_8.x {{ ansible_distribution_release }} main"

- name: Install nodejs and friends
  become: true
  apt:
    name: nodejs

- name: Add Yarn deb signing key
  become: true
  apt_key:
    url: https://dl.yarnpkg.com/debian/pubkey.gpg

- name: Add Yarn apt repository
  become: true
  apt_repository:
    repo: "deb https://dl.yarnpkg.com/debian/ stable main"

- name: Install Yarn
  become: true
  apt:
    package: yarn

- name: Create ~/.npm-global
  file:
    path: ~/.npm-global
    state: directory

- name: Configure NPM prefix
  command: npm config set prefix '~/.npm-global'

- name: Add ~/.npm-global to PATH
  include: roles/bashrc/tasks/bashrc.yml name=npm-global-path src=files/npm-global-path.sh priority=20
