- name: Install SBT
  become: true
  pacman:
    name: sbt

- name: Install Scalastyle
  aur:
    name: scalastyle
    user: "{{ ansible_user_id }}"

- name: Create ~/.sbt/0.13/plugins
  file:
    path: ~/.sbt/0.13/plugins
    state: directory
    recurse: true

- name: Symlink Scala-related symlinks
  include: roles/dotfiles/tasks/symlink.yml src={{ item }}
  with_items:
   - .sbt/0.13/plugins/build.sbt
   - .sbt/0.13/plugins/plugins.sbt
   - .sbt/0.13/global.sbt
