- name: Figure out root dir name of IDEA distribution
  shell: tar tzf ~/.ansible/idea.tar.gz | head -n1 | sed -e 's/\/.*//'
  register: idea_path

- name: Unarchive IntelliJ IDEA Ultimate {{ intellij.idea.version }}
  become: true
  unarchive:
    src: ~/.ansible/idea.tar.gz
    dest: /opt/

- name: Symlink IntelliJ IDEA Ultimate {{ intellij.idea.version }} idea.sh to /usr/local/bin/idea
  become: true
  file:
    src: /opt/{{ idea_path.stdout }}/bin/idea.sh
    dest: /usr/local/bin/idea
    state: link
