- name: Download IntelliJ IDEA Ultimate {{ intellij.idea.version }}
  get_url:
    url: https://download.jetbrains.com/idea/ideaIU-{{ intellij.idea.version }}.tar.gz
    checksum: "{{ intellij.idea.checksum }}"
    dest: /tmp/idea.tar.gz

- name: Figure out root dir name of IDEA distribution
  shell: tar tzf /tmp/idea.tar.gz | head -n1 | sed -e 's/\/.*//'
  register: idea_path

- name: Unarchive IntelliJ IDEA Ultimate {{ intellij.idea.version }}
  become: true
  unarchive:
    src: /tmp/idea.tar.gz
    dest: /opt/

- name: Symlink IntelliJ IDEA Ultimate {{ intellij.idea.version }} idea.sh to /usr/local/bin/idea
  become: true
  file:
    src: /opt/{{ idea_path.stdout }}/bin/idea.sh
    dest: /usr/local/bin/idea
    state: link

- name: Save IntelliJ IDEA Ultimate {{ intellij.idea.version }} version to state file
  copy:
    content: "{{ intellij.idea.version }}"
    dest: ~/.idea-version
