- name: Download IntelliJ IDEA Ultimate {{ intellij.idea.version }}
  get_url:
    url: https://download.jetbrains.com/idea/ideaIU-{{ intellij.idea.version }}.tar.gz
    checksum: "{{ intellij.idea.checksum }}"
    dest: ~/.ansible/idea.tar.gz
  register: idea_download

- name: Install IntelliJ IDEA Ultimate {{ intellij.idea.version }}
  include: install.yml
