- name: Install python env management tools
  aur:
    name: "{{ item }}"
  with_items:
    - pyenv
    - pyenv-virtualenv
    - python-pipenv

- name: Install dependencies for building Pythons via pyenv
  become: true
  pacman:
    name: "{{ item }}"
  with_items:
    - bzip2
    - readline

- name: Install pip
  become: true
  pacman:
    name: python-pip

- name: Install dependencies commonly used by Python modules
  become: true
  pacman:
    name: "{{ item }}"
  with_items:
    - libxml2
    - libxslt
    - swig

- name: Install Python code quality tools
  become: true
  pacman:
    name: "{{ item }}"
  with_items:
    - flake8
    - python-pylint
