- name: Install base-devel so that we can build packages
  become: true
  package:
    name: base-devel

- name: Install yay AUR helper
  aur:
    name: yay

- name: Symlink yay config from dotfiles
  include: roles/dotfiles/tasks/symlink.yml src=.config/yay force=true
