- name: Download Adobe Source Code Pro {{ adobe_source_code_pro.version }}
  get_url:
    url: https://github.com/adobe-fonts/source-code-pro/archive/{{ adobe_source_code_pro.version }}.tar.gz
    dest: ~/.ansible/adobe-source-code-pro.tar.gz
    checksum: "{{ adobe_source_code_pro.checksum }}"
  notify: Install Adobe Source Code Pro
