- name: Download Adobe Source Code Pro {{ adobe_source_code_pro.version }}
  get_url:
    url: https://github.com/adobe-fonts/source-code-pro/archive/{{ adobe_source_code_pro.version }}.tar.gz
    dest: ~/.ansible/adobe-source-code-pro.tar.gz
    checksum: "{{ adobe_source_code_pro.checksum }}"
  register: adobe_source_code_pro_download

- name: Install Adobe Source Code Pro
  include: install.yml
  when: "{{ adobe_source_code_pro_download.changed }}"
