- name: Check if prey is installed and up to date
  shell: 'apt-cache policy prey | grep "Installed: {{ prey.version }}"'
  register: prey_installed
  ignore_errors: yes

- when: prey_installed.rc != 0
  # Installing with apt/deb or downloading with get_url fails with fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Failure downloading https://downloads.preyproject.com/prey-client-releases/node-client/1.6.6/prey_1.6.6_i386.deb, 'NoneType' object has no attribute 'read'"}
  block:
    - name: Download prey {{ prey.version }}
      command: wget --quiet --continue --output-document=/tmp/prey_{{ prey.version }}.deb https://downloads.preyproject.com/prey-client-releases/node-client/{{ prey.version }}/prey_{{ prey.version }}_amd64.deb
    - name: Install prey {{ prey.version }}
      become: true
      pacman:
        name: /tmp/prey_{{ prey.version }}.deb
