- name: Install common tools
  become: true
  apt:
    name: "{{ item }}"
  with_items:
    - silversearcher-ag
    - unzip
    - wget
    - curl
    - jq
    - tree
    - pcregrep
    - net-tools
    - whois
