- name: Install common tools
  become: true
  pacman:
    name: "{{ item }}"
  with_items:
    - the_silver_searcher
    - ripgrep
    - unzip
    - wget
    - curl
    - jq
    - tree
    - pcre
    - net-tools
    - whois
    - hwinfo
    - bat
