- name: Install diagnostic tools
  become: true
  pacman:
    name: "{{ item }}"
  with_items:
    - htop
    - atop
    - iotop
    - nethogs
    - ngrep
    - wireshark-gtk
    - acpi

- name: Add {{ ansible_user_id }} to wireshark group
  become: true
  user:
    name: "{{ ansible_user_id }}"
    append: yes
    groups: wireshark
