- name: Install wicd
  become: true
  pacman:
    name: "{{ item }}"
  with_items:
    - wicd
    - wicd-gtk

- name: Enable wicd in SystemD
  become: true
  systemd:
    enabled: true
    name: wicd
