- name: Create ~/vpn
  file:
    path: ~/vpn
    state: directory

- name: Emit VPN config files
  copy:
    dest: ~/vpn/{{ item }}
    content: "{{ lookup('lastpass', 'vpn/' + item, field='notes') }}"
    mode: 0600
  with_items:
    - ca.crt
    - client.crt
    - client.key
    - prezi.ovpn
    - ta.key

- name: Create ~/.config/systemd/user
  file:
    path: ~/.config/systemd/user
    state: directory
    recurse: true

- name: VPN systemd unit
  become: true
  copy:
    src: roles/network/files/vpn.service
    dest: /lib/systemd/system/vpn.service
  register: vpn_systemd_unit

- name: Set VPN systemd unit to disabled and reload systemd daemon if the unit file changed
  when: vpn_systemd_unit.changed
  become: true
  systemd:
    name: vpn
    enabled: false
