- name: Install volume control
  become: true
  apt:
    name: "{{ item }}"
  with_items:
    - pasystray
    - paman
    - paprefs
    - pavucontrol
    - pavumeter
    - pulseaudio-module-zeroconf
    - pnmixer

- name: Start volume control (paman) in xprofile
  include: roles/xprofile/tasks/xprofile.yml name=pnmixer src=pnmixer priority=20

- name: Check if pulseaudio-ctl is installed and up to date
  shell: 'pulseaudio-ctl | head -n1 | grep -F "pulseaudio-ctl v{{ pulseaudio_ctl.version }}"'
  register: pulseaudio_ctl_installed
  ignore_errors: true

- when: pulseaudio_ctl_installed.rc != 0
  block:
    - name: Download pulseaudio-ctl {{ pulseaudio_ctl.version }}
      get_url:
        url: https://github.com/graysky2/pulseaudio-ctl/archive/v{{ pulseaudio_ctl.version }}.tar.gz
        dest: /tmp/pulseaudio-ctl.tar.gz
    - name: Extract pulseaudio-ctl {{ pulseaudio_ctl.version }}
      unarchive:
        src: /tmp/pulseaudio-ctl.tar.gz
        dest: /tmp/
    - name: Install pulseaudio_ctl {{ pulseaudio_ctl.version }}
      become: true
      make:
        chdir: /tmp/pulseaudio-ctl-{{ pulseaudio_ctl.version }}
        target: install
