- name: Install PulseAudio and volume control
  become: true
  pacman:
    name: "{{ item }}"
  with_items:
    - alsa-utils
    - pulseaudio
    - paprefs
    - pavucontrol
    - pulseaudio-zeroconf

- name: Install volume control components from AUR
  with_items:
    - paman
    - pasystray
    - pnmixer
    - pulseaudio-ctl
  aur:
    name: "{{ item }}"

- name: Configure pnmixer
  include: roles/dotfiles/tasks/symlink.yml src=.config/pnmixer

- name: Start volume control (pnmixer) in xprofile
  include: roles/xprofile/tasks/xprofile.yml name=pnmixer src=pnmixer priority=20
