- name: Install UFW
  become: true
  pacman:
    name: ufw

- name: Enable UFW
  become: true
  ufw:
    state: enabled

- name: Enable UFW logging (level=low)
  become: true
  ufw:
    logging: low

- name: Enable outgoing traffic on UFW
  become: true
  ufw:
    rule: allow
    direction: out
