- name: Symlink git configuration
  include: roles/dotfiles/tasks/symlink.yml src=.gitconfig

- name: Install git-so-fancy
  become: true
  npm:
    name: diff-so-fancy
    global: true

- name: Set up PPA for hub GitHub client
  become: true
  apt_repository:
    repo: ppa:cpick/hub

- name: Install hub GitHub client
  become: true
  apt:
    name: hub
