- name: Symlink git configuration
  include: roles/dotfiles/tasks/symlink.yml src=.gitconfig

- name: Install git-so-fancy
  become: true
  pacman:
    name: diff-so-fancy

- name: Install hub GitHub client
  become: true
  pacman:
    name: hub
