- name: Check if Slack is installed and up to date
  shell: 'apt-cache policy slack-desktop | grep "Installed: {{ slack.version }}"'
  register: slack_installed
  ignore_errors: yes

- when: slack_installed.rc != 0
  name: Install Slack {{ slack.version }}
  become: true
  apt:
    deb: https://downloads.slack-edge.com/linux_releases/slack-desktop-{{ slack.version }}-amd64.deb
