- name: Install dunst
  become: true
  package:
    name: dunst

- name: Start dunst in xprofile
  include: roles/xprofile/tasks/xprofile.yml
  vars:
    name: dunst
    priority: 20
    command: dunst &

- name: Symlink dunstrc
  include: roles/dotfiles/tasks/symlink.yml src=.config/dunst_{{ ansible_local.display_resolution.name }} dest=~/.config/dunst
