- name: Install LastPass
  become: true
  pacman:
    name: lastpass-cli

- name: Disable usage of pinentry in LastPass CLI
  # because it uses a GUI if it can and it's annoying as hell
  include: roles/bashrc/tasks/bashrc.yml name=lastpass_disable_pinentry src=files/lastpass_disable_pinentry.sh priority=10
