- name: Install Oracle JDK 8
  aur:
    name: jdk8

- name: Install Java, Gradle, and Maven
  become: true
  pacman:
    name: "{{ item }}"
  with_items:
    - maven
    - gradle

- name: Create ~/.gradle
  file:
    path: ~/.gradle
    state: directory

- name: Symlink gradle config
  include: roles/dotfiles/tasks/symlink.yml src=.gradle/init.gradle
