- name: Fetch Google Chrome PPA signing key
  become: true
  apt_key:
    url: 'https://dl-ssl.google.com/linux/linux_signing_key.pub'
    state: present

- name: Add Google Chrome apt repo
  become: true
  apt_repository:
    repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
    state: present
    filename: 'google-chrome'

- name: Install Google Chrome
  become: true
  apt:
    name: google-chrome-stable
    state: latest
