- name: Dell XPS 15 touchpad quirk
  become: true
  copy:
    src: 51-synaptics-xps15.conf
    dest: /usr/share/X11/xorg.conf.d/51-synaptics-xps15.conf

- name: Enable synaptic tweaks (synclient, syndaemon calsl)
  include: roles/xprofile/tasks/xprofile.yml name=synaptics-tweaks priority=20 src=synaptics-tweaks

- name: Install power / heat management utilities
  become: true
  apt:
    name: "{{ item }}"
  with_items:
    - powertop
    - powerstat
    - pm-utils
    - laptop-mode-tools
    - lm-sensors

- name: Enable SATA Link Power Management
  become: true
  copy:
    dest: /etc/pm/config.d/sata_alpm
    content: SATA_ALPM_ENABLE=true

- name: Graphics Drivers PPA
  become: true
  apt_repository:
    repo: ppa:graphics-drivers/ppa

- name: Install display drivers
  become: true
  apt:
    package: "{{ item }}"
  with_items:
    - nvidia-384
    - xserver-xorg-video-intel
    - nvidia-prime

- name: Enable TearFree on Xorg
  become: true
  copy:
    src: 20-tearfree.conf
    dest: /usr/share/X11/xorg.conf.d/20-tearfree.conf

- name: Install Bluetooth firmware
  become: true
  copy:
    src: BCM-0a5c-6410.hcd
    dest: /lib/firmware/brcm/BCM-0a5c-6410.hcd

- name: Install Bluetooth utilities
  become: true
  apt:
    name: "{{ item }}"
  with_items:
    - bluez
    - bluez-tools
    - blueman
