- name: Install tmux
  become: true
  apt:
    name: tmux
    state: latest

- name: Create ~/.tmux/plugins
  file:
    path: ~/.tmux.plugins
    state: directory
    recurse: true

- name: Install tpm (tmux package manager)
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: ~/.tmux/plugins/tpm
    update: no

- name: Symlink .tmux.conf
  include: roles/dotfiles/tasks/symlink.yml src=.tmux.conf

- name: Install tmux plugins
  shell: TMUX_PLUGIN_MANAGER_PATH=~/.tmux/plugins ~/.tmux/plugins/tpm/bin/install_plugins

- name: Check if tmux-cssh is installed and up to date
  shell: 'apt-cache policy tmux-cssh | grep "Installed: 1.0.6-0"'
  register: tmux_cssh_installed
  ignore_errors: true

- name: Install tmux-cssh
  when: tmux_cssh_installed.rc != 0
  become: true
  apt:
    deb: https://raw.githubusercontent.com/dennishafemann/tmux-cssh/deb-package/deb-packages/tmux-cssh_1.0.6-0.deb
