- name: Install Dropbox and friends
  aur:
    name: "{{ item }}"
    user: "{{ ansible_user_id }}"
  with_items:
    - dropbox
    - dropbox-cli

- name: Auto-start Dropbox from .xprofile.d
  include: roles/xprofile/tasks/xprofile.yml name=dropbox src=dropbox priority=30
