- name: Check if keybase is installed and up to date
  shell: 'apt-cache policy keybase | grep "Installed: {{ keybase.version }}"'
  register: keybase_installed
  ignore_errors: yes

- when: keybase_installed.rc != 0
  block:
    - name: Add keybase apt signing key
      become: true
      apt_key:
        url: https://keybase.io/docs/server_security/code_signing_key.asc
        id: 222B85B0F90BE2D24CFEB93F47484E50656D16C7

    - name: Install keybase {{ keybase.version }}
      become: true
      apt:
        deb: https://prerelease.keybase.io/keybase_amd64.deb
