- name: Install keybase
  with_items:
    - keybase
    - keybase-gui
    - kbfs
  package:
    name: "{{ item }}"

- name: Start Keybase on login
  systemd:
    name: "{{ item }}"
    enabled: true
    state: started
    user: true
  with_items:
    - keybase
    - kbfs
    # _not_ keybase.gui, can start that on demand as needed
