- name: Install LightDM and friends
  become: true
  pacman:
    name: "{{ item }}"
  with_items:
    - xorg-server
    - xorg-apps
    - lightdm

- name: Install LightDM mini greeter
  aur:
    name: lightdm-mini-greeter
    user: "{{ ansible_user_id }}"

- name: Install LightDM configuration
  become: true
  copy:
    src: roles/lightdm/files/lightdm.conf
    dest: /etc/lightdm/lightdm.conf

- name: Install the LightDM mini greeter configuration
  become: true
  template:
    src: roles/lightdm/templates/lightdm-mini-greeter.conf
    dest: /etc/lightdm/lightdm-mini-greeter.conf

- name: Enable LightDM in SystemD
  become: true
  systemd:
    enabled: true
    name: lightdm
