- name: Install Docker
  become: true
  pacman:
    name: docker

- name: Start, enable Docker service
  become: true
  systemd:
    name: docker
    enabled: true
    state: started

- name: Create docker group
  group:
    name: docker

- name: Add user to docker group
  become: true
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: true

- name: Install docker-compose
  become: true
  pacman:
    name: docker-compose
