- name: Check if WMail is installed and up to date
  shell: 'apt-cache policy wmail-desktop | grep "Installed: {{ wmail.version }}"'
  register: wmail_installed
  ignore_errors: yes

- when: wmail_installed.rc != 0
  block:
    - name: Download WMail {{ wmail.version }}
      get_url:
        url: https://github.com/Thomas101/wmail/releases/download/v{{ wmail.version }}/WMail_{{ wmail.version | replace('.', '_') }}_linux_x86_64.deb
        dest: /tmp/wmail.deb
    - name: Install WMail {{ wmail.version }}
      become: true
      apt:
        deb: /tmp/wmail.deb

- name: Symlink WMail
  become: true
  file:
    src: /opt/wmail-desktop/WMail
    dest: /usr/local/bin/wmail
    state: link
