- name: Install XMonad and friends
  become: true
  pacman:
    name: "{{ item }}"
  with_items:
    - xmonad
    - xmonad-contrib
    - dmenu
    - xmobar
    - stalonetray
    - scrot
    - gpicview
    - xorg-xbacklight
    - xclip
    - parcellite
    - light-locker

- name: Install Yegonesh
  aur:
    name: yegonesh

- file:
    path: ~/.config/xmobar
    state: directory

- name: Symlink configuration for XMonad
  include: roles/dotfiles/tasks/symlink.yml src=.xmonad

- name: Symlink xmobar configuration
  include: roles/dotfiles/tasks/symlink.yml src=.config/xmobar/xmobarrc_{{ site }} dest=~/.config/xmobar/xmobarrc

- name: Symlink stalonetray configuration
  include: roles/dotfiles/tasks/symlink.yml dest=~/.stalonetrayrc src=.stalonetrayrc_{{ ansible_local.display_resolution.name }}
  with_items:
    - .stalonetrayrc

- name: Start stalonetray from .xprofile
  include: roles/xprofile/tasks/xprofile.yml name=stalonetray src=stalonetray priority=20

- name: Start light-locker from .xprofile
  include: roles/xprofile/tasks/xprofile.yml name=light-locker src=light-locker priority=20

- name: Start parcellite clipboard manager from .xprofile
  include: roles/xprofile/tasks/xprofile.yml name=parcellite src=parcellite priority=20

- name: Set keyboard repeat rate
  include: roles/xprofile/tasks/xprofile.yml name=keyboard-repeat src=keyboard-repeat priority=20

- name: Disable mouse acceleration
  include: roles/xprofile/tasks/xprofile.yml name=disable-mouse-acceleration src=disable-mouse-acceleration priority=20

- name: Create systemd unit to lock screen on suspend
  become: true
  copy:
    src: files/lock-on-suspend@.service
    dest: /etc/systemd/system/lock-on-suspend@.service

- name: Enable systemd unit to lock screen on suspend
  become: true
  systemd:
    name: lock-on-suspend@{{ ansible_user_id }}
    enabled: true
    daemon_reload: true

- name: Set root X cursor to left pointer
  include: roles/xprofile/tasks/xprofile.yml name=xsetroot-cursor src=xsetroot-cursor priority=20
