- name: Install XMonad and friends
  become: true
  apt: name={{ item }} state=latest
  with_items:
    - xmonad
    - libghc-xmonad-contrib-dev
    - dmenu
    - xmobar
    - stalonetray
    - scrot
    - cabal-install
    - gpicview
    - xbacklight

- name: Install yeganesh with cabal
  shell: cabal update; cabal install yeganesh
  args:
    creates: ~/.cabal/bin/yeganesh

# If this repo ever decides to include a Haskell devenv, this should move there
- name: Add cabal bin dir to path
  include: roles/bashrc/tasks/bashrc.yml name=cabal-bin-path src=files/cabal-bin-path.sh priority=20

- name: Set XMonad as default LightDM session
  become: true
  copy:
    src: files/50-xmonad.conf
    dest: /etc/lightdm/lightdm.conf.d/50-xmonad.conf
  notify:
    - restart lightdm

- file:
    path: ~/.config/xmobar
    state: directory

- name: Symlink configuration for XMonad
  include: roles/dotfiles/tasks/symlink.yml src=.xmonad

- name: Symlink xmobar configuration
  include: roles/dotfiles/tasks/symlink.yml src=.config/xmobar/xmobarrc_{{ site }} dest=~/.config/xmobar/xmobarrc

- name: Symlink stalonetray configuration
  include: roles/dotfiles/tasks/symlink.yml dest=~/.stalonetrayrc src=.stalonetrayrc_{{ ansible_local.display_resolution.name }}
  with_items:
    - .stalonetrayrc

- name: Start stalonetray from .xprofile
  include: roles/xprofile/tasks/xprofile.yml name=stalonetray src=stalonetray priority=20

- name: Set keyboard repeat rate
  include: roles/xprofile/tasks/xprofile.yml name=keyboard-repeat src=keyboard-repeat priority=20

- name: Disable mouse acceleration
  include: roles/xprofile/tasks/xprofile.yml name=disable-mouse-acceleration src=disable-mouse-acceleration priority=20

- name: Create systemd unit to lock screen on suspend
  become: true
  copy:
    src: files/lock-on-suspend@.service
    dest: /etc/systemd/system/lock-on-suspend@.service

- name: Enable systemd unit to lock screen on suspend
  become: true
  systemd:
    name: lock-on-suspend@{{ ansible_user_id }}
    enabled: true
    daemon_reload: true

- name: Start gnome-screensaver on login
  include: roles/xprofile/tasks/xprofile.yml name=gnome-screensaver src=gnome-screensaver priority=20
