- name: Install XMonad and friends
  become: true
  apt: name={{ item }} state=latest
  with_items:
    - xmonad
    - libghc-xmonad-contrib-dev
    - dmenu
    - xmobar
    - stalonetray
    - scrot
    - cabal-install
    - gpicview

- name: Install yeganesh with cabal
  shell: cabal update; cabal install yeganesh
  args:
    creates: ~/.cabal/bin/yeganesh

# If this repo ever decides to include a Haskell devenv, this should move there
- name: Add cabal bin dir to path
  include: roles/bashrc/tasks/bashrc.yml name=cabal-bin-path src=files/cabal-bin-path.sh priority=20

- name: Set XMonad as default LightDM session
  become: true
  copy:
    src: files/50-xmonad.conf
    dest: /etc/lightdm/lightdm.conf.d/50-xmonad.conf
  notify:
    - restart lightdm

- file:
    path: ~/.config/xmobar
    state: directory

- name: Symlink XMonad configuration
  include: roles/dotfiles/tasks/symlink.yml src={{ item }}
  with_items:
    - .xmonad
    - .config/xmobar/xmobarrc

- name: Start stalonetray from .xprofile
  include: roles/xprofile/tasks/xprofile.yml name=stalonetray src=stalonetray priority=20

- name: Set keyboard repeat rate
  include: roles/xprofile/tasks/xprofile.yml name=keyboard-repeat src=keyboard-repeat priority=20
