- name: Install Nerd Fonts
  aur:
    name: nerd-fonts-complete
    user: "{{ ansible_user_id }}"

- name: Install Adobe Source Code Pro fonts
  become: true
  pacman:
    name: adobe-source-code-pro-fonts
